version: "3"
services: 
    db:
        image: mysql
        volumes: 
            - ".docker/mysql/config:/etc/mysql/conf.d/config-file.cnf"
            - ".docker/mysql/data:/var/lib/mysql:rw"
        container_name: mysql_nuvem
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports:
            - "3307:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
                
    adminer:
        container_name: Adminer_nuvem
        image: adminer
        restart: always
        ports:
            - 8081:8080